/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextArea;

/**
 *
 * @author Savin
 */
public class GlavnaForma extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GlavnaForma.class.getName());

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelSportista = new javax.swing.JLabel();
        jComboBoxSportisti = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jSpinnerDatumRez = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaNapomena = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableStavkeRezervacije = new javax.swing.JTable();
        jButtonDodajStavku = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabelUkupanIznos = new javax.swing.JLabel();
        jButtonKreirajRezervaciju = new javax.swing.JButton();
        jButtonUkloniStavku = new javax.swing.JButton();
        jButtonSacuvajIzmene = new javax.swing.JButton();
        jButtonIzmeniStavku = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemPrikazRezervacija = new javax.swing.JMenuItem();
        jMenuTerminDezurstva = new javax.swing.JMenu();
        jMenuItemDodajTermin = new javax.swing.JMenuItem();
        jMenuItemPrikaziTermine = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Zdravo,");

        jLabelSportista.setText("Sportista:");

        jLabel4.setText("Datum rezervacije:");

        jSpinnerDatumRez.setModel(new javax.swing.SpinnerDateModel());

        jLabel5.setText("Napomena:");

        jTextAreaNapomena.setColumns(20);
        jTextAreaNapomena.setRows(5);
        jScrollPane1.setViewportView(jTextAreaNapomena);

        jTableStavkeRezervacije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableStavkeRezervacije);

        jButtonDodajStavku.setText("Dodaj stavku rezervacije");
        jButtonDodajStavku.addActionListener(this::jButtonDodajStavkuActionPerformed);

        jLabel6.setText("Ukupan iznos:");

        jButtonKreirajRezervaciju.setText("Kreiraj rezervaciju");

        jButtonUkloniStavku.setText("Ukloni stavku ");

        jButtonSacuvajIzmene.setText("Sačuvaj izmene");

        jButtonIzmeniStavku.setText("Izmeni stavku");

        jMenu1.setText("Sportista");

        jMenuItem1.setText("Dodaj sportistu");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Prikaz sportista");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Rezervacija");

        jMenuItemPrikazRezervacija.setText("Prikaz rezervacija");
        jMenuItemPrikazRezervacija.addActionListener(this::jMenuItemPrikazRezervacijaActionPerformed);
        jMenu3.add(jMenuItemPrikazRezervacija);

        jMenuBar1.add(jMenu3);

        jMenuTerminDezurstva.setText("Termin dežurstva");

        jMenuItemDodajTermin.setText("Dodaj termin dežurstva");
        jMenuItemDodajTermin.addActionListener(this::jMenuItemDodajTerminActionPerformed);
        jMenuTerminDezurstva.add(jMenuItemDodajTermin);

        jMenuItemPrikaziTermine.setText("Prikaži termine dežurstava");
        jMenuItemPrikaziTermine.addActionListener(this::jMenuItemPrikaziTermineActionPerformed);
        jMenuTerminDezurstva.add(jMenuItemPrikaziTermine);

        jMenuBar1.add(jMenuTerminDezurstva);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDodajStavku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(jButtonUkloniStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonIzmeniStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSportista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxSportisti, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerDatumRez, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonSacuvajIzmene, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonKreirajRezervaciju, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSportista)
                    .addComponent(jComboBoxSportisti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinnerDatumRez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jButtonDodajStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUkloniStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonIzmeniStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelUkupanIznos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonKreirajRezervaciju, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jButtonSacuvajIzmene, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        koordinator.Koordinator.getInstance().otvoriPrikazSportistaFormu();

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        koordinator.Koordinator.getInstance().otvoriDodajSportistuFormu();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemDodajTerminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajTerminActionPerformed
        try {
            koordinator.Koordinator.getInstance().otvoriDodajTerminDezurstvaFormu();
        } catch (Exception ex) {
            System.getLogger(GlavnaForma.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_jMenuItemDodajTerminActionPerformed

    private void jMenuItemPrikaziTermineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikaziTermineActionPerformed
        try {
            koordinator.Koordinator.getInstance().otvoriPrikazTerminaDezurstavaFormu();
        } catch (Exception ex) {
            System.getLogger(GlavnaForma.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_jMenuItemPrikaziTermineActionPerformed

    private void jButtonDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajStavkuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDodajStavkuActionPerformed

    private void jMenuItemPrikazRezervacijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikazRezervacijaActionPerformed
        koordinator.Koordinator.getInstance().otvoriPrikazRezervacijaFormu();
    }//GEN-LAST:event_jMenuItemPrikazRezervacijaActionPerformed
    public void postaviModIzmene() {
        jMenuBar1.setVisible(false);
        jButtonKreirajRezervaciju.setVisible(false);
        jButtonSacuvajIzmene.setVisible(true);
        jLabel3.setVisible(false);
    }

    public void postaviModKreiranja() {
        jMenuBar1.setVisible(true);
        jButtonKreirajRezervaciju.setVisible(true);
        jButtonSacuvajIzmene.setVisible(false);
        jLabel3.setVisible(true);
    }

    public void postaviWindowListener() {
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                if (jButtonSacuvajIzmene.isVisible()) {
                    koordinator.Koordinator.getInstance().resetujGlavnuFormu();
                    postaviModKreiranja();
                    postaviNaslov("Zdravo,");
                } else {
                    System.exit(0);
                }
            }
        });
    }

    public void postaviNaslov(String tekst) {
        jLabel1.setText(tekst);
    }

    /**
     * @param args the command line arguments
     */
    /**
     * @param args the command line arguments
     */
    public JLabel getjLabel3() {
        return jLabel3;
    }

    public JComboBox<String> getjComboBoxSportisti() {
        return jComboBoxSportisti;
    }

    public JLabel getjLabelUkupanIznos() {
        return jLabelUkupanIznos;
    }

    public JSpinner getjSpinnerDatumRez() {
        return jSpinnerDatumRez;
    }

    public JTable getjTableStavkeRezervacije() {
        return jTableStavkeRezervacije;
    }

    public JTextArea getjTextAreaNapomena() {
        return jTextAreaNapomena;
    }

    public JButton getjButtonSacuvajIzmene() {
        return jButtonSacuvajIzmene;
    }

    public JButton getjButtonIzmeniStavku() {
        return jButtonIzmeniStavku;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajStavku;
    private javax.swing.JButton jButtonIzmeniStavku;
    private javax.swing.JButton jButtonKreirajRezervaciju;
    private javax.swing.JButton jButtonSacuvajIzmene;
    private javax.swing.JButton jButtonUkloniStavku;
    private javax.swing.JComboBox<String> jComboBoxSportisti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelSportista;
    private javax.swing.JLabel jLabelUkupanIznos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemDodajTermin;
    private javax.swing.JMenuItem jMenuItemPrikazRezervacija;
    private javax.swing.JMenuItem jMenuItemPrikaziTermine;
    private javax.swing.JMenu jMenuTerminDezurstva;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerDatumRez;
    private javax.swing.JTable jTableStavkeRezervacije;
    private javax.swing.JTextArea jTextAreaNapomena;
    // End of variables declaration//GEN-END:variables

    public void addBtnDodajStavkuActionListener(ActionListener al) {
        jButtonDodajStavku.addActionListener(al);
    }

    public void addBtnKreirajRezervacijuActionListener(ActionListener al) {
        jButtonKreirajRezervaciju.addActionListener(al);
    }

    public void addBtnUkloniStavkuActionListener(ActionListener al) {
        jButtonUkloniStavku.addActionListener(al);
    }

    public void addBtnSacuvajIzmeneActionListener(ActionListener al) {
        jButtonSacuvajIzmene.addActionListener(al);
    }

    public void addBtnIzmeniStavkuActionListener(ActionListener al) {
        jButtonIzmeniStavku.addActionListener(al);
    }
}
