/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JSpinner;
import javax.swing.JTable;

/**
 *
 * @author Savin
 */
public class PrikazRezervacijaForma extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrikazRezervacijaForma.class.getName());

    /**
     * Creates new form PrikazRezervacijaForma
     */
    public PrikazRezervacijaForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRezervacije = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxSportista = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxZaposleni = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jSpinnerDatum = new javax.swing.JSpinner();
        jButtonPretrazi = new javax.swing.JButton();
        jButtonIzmeniRezervaciju = new javax.swing.JButton();
        jCheckBoxDatum = new javax.swing.JCheckBox();
        jComboBoxStolovi = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableRezervacije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableRezervacije);

        jLabel1.setText("Sportista:");

        jLabel2.setText("Zaposleni:");

        jLabel3.setText("Datum:");

        jSpinnerDatum.setModel(new javax.swing.SpinnerDateModel());

        jButtonPretrazi.setText("Pretraži");

        jButtonIzmeniRezervaciju.setText("Izmeni rezervaciju");

        jLabel4.setText("Sto:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxSportista, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxStolovi, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxDatum)
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(427, 427, 427)
                                .addComponent(jButtonIzmeniRezervaciju, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(445, 445, 445)
                                .addComponent(jButtonPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxDatum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jComboBoxSportista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jComboBoxZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jSpinnerDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxStolovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(13, 13, 13)
                .addComponent(jButtonPretrazi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonIzmeniRezervaciju, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    public JButton getjButtonIzmeniRezervaciju() {
        return jButtonIzmeniRezervaciju;
    }

    public void setjButtonIzmeniRezervaciju(JButton jButtonIzmeniRezervaciju) {
        this.jButtonIzmeniRezervaciju = jButtonIzmeniRezervaciju;
    }

    public JButton getjButtonPretrazi() {
        return jButtonPretrazi;
    }

    public void setjButtonPretrazi(JButton jButtonPretrazi) {
        this.jButtonPretrazi = jButtonPretrazi;
    }

    public JComboBox<String> getjComboBoxSportista() {
        return jComboBoxSportista;
    }

    public void setjComboBoxSportista(JComboBox<String> jComboBoxSportista) {
        this.jComboBoxSportista = jComboBoxSportista;
    }

    public JComboBox<String> getjComboBoxZaposleni() {
        return jComboBoxZaposleni;
    }

    public void setjComboBoxZaposleni(JComboBox<String> jComboBoxZaposleni) {
        this.jComboBoxZaposleni = jComboBoxZaposleni;
    }

    public JTable getjTableRezervacije() {
        return jTableRezervacije;
    }

    /**
     * @param args the command line arguments
     */
    public void setjTableRezervacije(JTable jTableRezervacije) {
        this.jTableRezervacije = jTableRezervacije;
    }

    public JCheckBox getjCheckBoxDatum() {
        return jCheckBoxDatum;
    }

    public void setjCheckBoxDatum(JCheckBox jCheckBoxDatum) {
        this.jCheckBoxDatum = jCheckBoxDatum;
    }

    public JSpinner getjSpinnerDatum() {
        return jSpinnerDatum;
    }

    public void setjSpinnerDatum(JSpinner jSpinnerDatum) {
        this.jSpinnerDatum = jSpinnerDatum;
    }

    public JComboBox<String> getjComboBoxStolovi() {
        return jComboBoxStolovi;
    }

    public void setjComboBoxStolovi(JComboBox<String> jComboBoxStolovi) {
        this.jComboBoxStolovi = jComboBoxStolovi;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIzmeniRezervaciju;
    private javax.swing.JButton jButtonPretrazi;
    private javax.swing.JCheckBox jCheckBoxDatum;
    private javax.swing.JComboBox<String> jComboBoxSportista;
    private javax.swing.JComboBox<String> jComboBoxStolovi;
    private javax.swing.JComboBox<String> jComboBoxZaposleni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerDatum;
    private javax.swing.JTable jTableRezervacije;
    // End of variables declaration//GEN-END:variables

    public void addBtnAzurirajActionListener(ActionListener actionListener){
    
    jButtonIzmeniRezervaciju.addActionListener(actionListener);
    }
    
    public void addBtnPretraziActionListener(ActionListener al) {
    jButtonPretrazi.addActionListener(al);
}
}
