/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.io.IOException;
import server.Server;

/**
 *
 * @author Savin
 */
public class ServerskaForma extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ServerskaForma.class.getName());

    Server server;
    /**
     * Creates new form ServerskaForma
     */
    public ServerskaForma() {
        initComponents();
        server = new Server();
        jLabel1.setText("");
        jButtonZaustaviServer.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPokreniServer = new javax.swing.JButton();
        jButtonZaustaviServer = new javax.swing.JButton();
        jLabelStatus = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuKonfiguracija = new javax.swing.JMenu();
        jMenuItemBaza = new javax.swing.JMenuItem();
        jMenuItemPort = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonPokreniServer.setText("POKRENI SERVER");
        jButtonPokreniServer.addActionListener(this::jButtonPokreniServerActionPerformed);

        jButtonZaustaviServer.setText("ZAUSTAVI SERVER");
        jButtonZaustaviServer.addActionListener(this::jButtonZaustaviServerActionPerformed);

        jLabelStatus.setText("Status:");

        jMenuKonfiguracija.setText("KONFIGURACIJA");

        jMenuItemBaza.setText("baza");
        jMenuItemBaza.addActionListener(this::jMenuItemBazaActionPerformed);
        jMenuKonfiguracija.add(jMenuItemBaza);

        jMenuItemPort.setText("port");
        jMenuItemPort.addActionListener(this::jMenuItemPortActionPerformed);
        jMenuKonfiguracija.add(jMenuItemPort);

        jMenuBar1.add(jMenuKonfiguracija);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButtonPokreniServer)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(jButtonZaustaviServer)
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStatus)
                    .addComponent(jLabel1))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPokreniServer)
                    .addComponent(jButtonZaustaviServer))
                .addGap(103, 103, 103))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemBazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBazaActionPerformed
        FormaKonfiguracijaBaza baza = new FormaKonfiguracijaBaza(this, false);
        baza.setVisible(true);

    }//GEN-LAST:event_jMenuItemBazaActionPerformed

    private void jMenuItemPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPortActionPerformed

        FormaKonfiguracijaPort port = new FormaKonfiguracijaPort(this, false);
        port.setVisible(true);

    }//GEN-LAST:event_jMenuItemPortActionPerformed

    private void jButtonPokreniServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPokreniServerActionPerformed


        server.start();
        jLabel1.setText("POKRENUT");
        jButtonZaustaviServer.setEnabled(true);
        jButtonPokreniServer.setEnabled(false);

    }//GEN-LAST:event_jButtonPokreniServerActionPerformed

    private void jButtonZaustaviServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZaustaviServerActionPerformed
        try {
            server.zaustaviServer();
        } catch (IOException ex) {
            System.getLogger(ServerskaForma.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
                jLabel1.setText("ZAUSTAVLJEN");
                jButtonPokreniServer.setEnabled(true);
                jButtonZaustaviServer.setEnabled(false);
                

    }//GEN-LAST:event_jButtonZaustaviServerActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPokreniServer;
    private javax.swing.JButton jButtonZaustaviServer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemBaza;
    private javax.swing.JMenuItem jMenuItemPort;
    private javax.swing.JMenu jMenuKonfiguracija;
    // End of variables declaration//GEN-END:variables
}
